name: CMake Tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ls -la

    # - name: Upload test results
    #   uses: actions/upload-artifact@v4
    #   if: failure()
    #   with:
    #     name: test_results_xml
    #     path: ${{runner.workspace}}/build/test-results/**/*.xml
